import os
import subprocess
import json
from pathlib import Path
from models.models import GitHook, Project, db
import uuid

class GitHookService:
    """Service for managing Git hooks for auto-documentation"""

    HOOK_TEMPLATE = """#!/bin/bash
# Auto-generated documentation hook
# Generated by Documentation Auto-Generator

# Configuration
PROJECT_ID="{project_id}"
API_ENDPOINT="{api_endpoint}"
HOOK_TYPE="{hook_type}"

# Get list of changed files
if [ "$HOOK_TYPE" = "pre-commit" ]; then
    CHANGED_FILES=$(git diff --cached --name-only)
elif [ "$HOOK_TYPE" = "post-commit" ]; then
    CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)
else
    CHANGED_FILES=$(git diff --name-only)
fi

# Trigger documentation update via API
if [ ! -z "$CHANGED_FILES" ]; then
    curl -X POST "$API_ENDPOINT/api/docs/auto-update" \\
        -H "Content-Type: application/json" \\
        -d "{{
            \\"project_id\\": \\"$PROJECT_ID\\",
            \\"changed_files\\": $(echo "$CHANGED_FILES" | jq -R . | jq -s .),
            \\"hook_type\\": \\"$HOOK_TYPE\\"
        }}" \\
        --max-time 10 \\
        --silent || echo "Documentation update triggered"
fi
"""

    def __init__(self):
        self.api_endpoint = os.getenv('API_ENDPOINT', 'http://localhost:5000')

    def install_hook(self, project_id, hook_type='post-commit', config=None):
        """
        Install a Git hook for automatic documentation generation

        Args:
            project_id: Project to install hook for
            hook_type: Type of hook (pre-commit, post-commit, post-merge)
            config: Optional configuration dict

        Returns:
            GitHook model instance
        """
        project = Project.query.get(project_id)

        if not project or not project.local_path:
            raise ValueError('Project not found or has no local path')

        git_hooks_dir = os.path.join(project.local_path, '.git', 'hooks')

        # Create hooks directory if it doesn't exist
        os.makedirs(git_hooks_dir, exist_ok=True)

        # Generate hook script
        hook_script = self.HOOK_TEMPLATE.format(
            project_id=project_id,
            api_endpoint=self.api_endpoint,
            hook_type=hook_type
        )

        # Write hook file
        hook_file = os.path.join(git_hooks_dir, hook_type)

        with open(hook_file, 'w') as f:
            f.write(hook_script)

        # Make executable
        os.chmod(hook_file, 0o755)

        # Create database record
        git_hook = GitHook(
            id=str(uuid.uuid4()),
            project_id=project_id,
            hook_type=hook_type,
            enabled=True,
            config=config or {}
        )

        db.session.add(git_hook)
        db.session.commit()

        return git_hook

    def uninstall_hook(self, project_id, hook_type):
        """
        Uninstall a Git hook

        Args:
            project_id: Project to uninstall hook from
            hook_type: Type of hook to remove

        Returns:
            Boolean success
        """
        project = Project.query.get(project_id)

        if not project or not project.local_path:
            return False

        hook_file = os.path.join(project.local_path, '.git', 'hooks', hook_type)

        # Remove hook file
        try:
            if os.path.exists(hook_file):
                os.remove(hook_file)

            # Remove database record
            GitHook.query.filter_by(
                project_id=project_id,
                hook_type=hook_type
            ).delete()

            db.session.commit()

            return True

        except Exception as e:
            print(f'Error uninstalling hook: {e}')
            return False

    def get_project_hooks(self, project_id):
        """Get all hooks for a project"""
        return GitHook.query.filter_by(project_id=project_id).all()

    def enable_hook(self, hook_id):
        """Enable a disabled hook"""
        hook = GitHook.query.get(hook_id)

        if hook:
            hook.enabled = True
            db.session.commit()
            return True

        return False

    def disable_hook(self, hook_id):
        """Disable a hook without uninstalling"""
        hook = GitHook.query.get(hook_id)

        if hook:
            hook.enabled = False
            db.session.commit()
            return True

        return False

    def setup_github_webhook(self, project_id, github_repo, webhook_secret):
        """
        Setup GitHub webhook for PR and commit events

        Args:
            project_id: Project ID
            github_repo: GitHub repository (owner/repo)
            webhook_secret: Secret for webhook verification

        Returns:
            Webhook URL and configuration
        """
        webhook_url = f"{self.api_endpoint}/api/docs/github-webhook"

        # Store webhook configuration
        config = {
            'github_repo': github_repo,
            'webhook_secret': webhook_secret,
            'webhook_url': webhook_url,
            'events': ['push', 'pull_request']
        }

        git_hook = GitHook(
            id=str(uuid.uuid4()),
            project_id=project_id,
            hook_type='github-webhook',
            enabled=True,
            config=config
        )

        db.session.add(git_hook)
        db.session.commit()

        return {
            'webhook_url': webhook_url,
            'events': ['push', 'pull_request'],
            'content_type': 'application/json',
            'secret': webhook_secret
        }

    def handle_commit_event(self, project_id, commit_data):
        """
        Handle a commit event and trigger documentation updates

        Args:
            project_id: Project that had a commit
            commit_data: Commit information including changed files

        Returns:
            Job ID for documentation update
        """
        from services.queue_service import QueueService
        queue_service = QueueService()

        # Extract changed files
        changed_files = commit_data.get('changed_files', [])

        if not changed_files:
            return None

        # Enqueue documentation generation job
        job_id = queue_service.enqueue_documentation_update(
            project_id,
            changed_files,
            commit_data.get('commit_sha'),
            commit_data.get('commit_message')
        )

        return job_id

    def handle_pr_event(self, project_id, pr_data):
        """
        Handle a pull request event and check for documentation drift

        Args:
            project_id: Project with the PR
            pr_data: Pull request information

        Returns:
            Drift check results
        """
        from services.drift_detection_service import DriftDetectionService
        drift_service = DriftDetectionService()

        # Get changed files in PR
        changed_files = pr_data.get('changed_files', [])

        # Check for drift
        drifts = drift_service.check_project_for_drift(project_id, changed_files)

        # If drift detected, add comment to PR (would need GitHub API)
        if drifts:
            return {
                'has_drift': True,
                'drift_count': len(drifts),
                'drifts': [
                    {
                        'file': d.file_path,
                        'severity': d.severity,
                        'description': d.drift_description
                    }
                    for d in drifts
                ]
            }

        return {'has_drift': False, 'drift_count': 0}

    def create_pre_commit_config(self, project_id):
        """
        Create a pre-commit configuration file for the project

        This allows documentation checks before commits
        """
        project = Project.query.get(project_id)

        if not project or not project.local_path:
            return None

        pre_commit_config = {
            'repos': [
                {
                    'repo': 'local',
                    'hooks': [
                        {
                            'id': 'check-docs-drift',
                            'name': 'Check documentation drift',
                            'entry': f'python -m doc_checker {project_id}',
                            'language': 'system',
                            'pass_filenames': False
                        }
                    ]
                }
            ]
        }

        config_file = os.path.join(project.local_path, '.pre-commit-config.yaml')

        import yaml
        with open(config_file, 'w') as f:
            yaml.dump(pre_commit_config, f)

        return config_file
